#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 14 12:06:42 EDT 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim lab2_2test_behav -key {Behavioral:sim_1:Functional:lab2_2test} -tclbatch lab2_2test.tcl -log simulate.log"
xsim lab2_2test_behav -key {Behavioral:sim_1:Functional:lab2_2test} -tclbatch lab2_2test.tcl -log simulate.log

