# Assign inputs/outputs to actual pins on the FPGA
set_property PACKAGE_PIN M15 [get_ports {clk}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property PACKAGE_PIN H17 [get_ports {regaddr[4]}]
set_property PACKAGE_PIN H18 [get_ports {regaddr[3]}]
set_property PACKAGE_PIN H19 [get_ports {regaddr[2]}]
set_property PACKAGE_PIN F21 [get_ports {regaddr[1]}]
set_property PACKAGE_PIN H22 [get_ports {regaddr[0]}]
set_property PACKAGE_PIN G22 [get_ports {datasection[1]}]
set_property PACKAGE_PIN F22 [get_ports {datasection[0]}]
set_property PACKAGE_PIN U14 [get_ports {outdata[7]}]
set_property PACKAGE_PIN U19 [get_ports {outdata[6]}]
set_property PACKAGE_PIN W22 [get_ports {outdata[5]}]
set_property PACKAGE_PIN V22 [get_ports {outdata[4]}]
set_property PACKAGE_PIN U21 [get_ports {outdata[3]}]
set_property PACKAGE_PIN U22 [get_ports {outdata[2]}]
set_property PACKAGE_PIN T21 [get_ports {outdata[1]}]
set_property PACKAGE_PIN T22 [get_ports {outdata[0]}]
set_property PACKAGE_PIN R16 [get_ports {reset}]
# Define voltage levels (3.3 for LEDs and 1.8 for Switches)

set_property IOSTANDARD LVCMOS18 [get_ports {clk}]
set_property IOSTANDARD LVCMOS18 [get_ports {regaddr[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {regaddr[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {regaddr[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {regaddr[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {regaddr[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datasection[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datasection[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outdata[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {reset}]