#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 06 15:02:13 EST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto fc420bd8a4a24304bfc1abc4ee2d7fbc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lab5_4testFile_behav xil_defaultlib.lab5_4testFile xil_defaultlib.glbl -log elaborate.log"
xelab -wto fc420bd8a4a24304bfc1abc4ee2d7fbc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lab5_4testFile_behav xil_defaultlib.lab5_4testFile xil_defaultlib.glbl -log elaborate.log

